# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.10.0
_src_path: gh:radio-aktywne/template-devcontainer
accountname: radio-aktywne
description: Devcontainer for NestJS services 🐈
devcontainername: service-nest
docs: true
docsurl: https://radio-aktywne.github.io/devcontainer-service-nest
imagename: devcontainers/service-nest
registry: true
releases: true
reponame: devcontainer-service-nest
repourl: https://github.com/radio-aktywne/devcontainer-service-nest
